### ISSUE TITLE
Data saving

### ISSUE THREAD

**Issue by pietru2004** [bitbrain/pandora#104]
I just wana say that in docs I think it could be more practical in some cases to just save ammount of item user has
![obraz](https://github.com/bitbrain/pandora/assets/51274570/fda4323a-0e17-480a-a786-e262c9b76f76)
There might be array holding all items players has or dictionary holding item key and item ammount... or mayby even array holding array or dictionary that has item reference/id and count

Also is it safe to use this for experimental project? I mean project idea that is in alpha/prototype.

And please add question template for issues (for questions 😄 )...

**Comment by mrfelipemartins** [comment]
I believe for that to be possible we need #54 and #95 

Pandora is currently in its alpha stage, however, considering your project is also in the alpha/prototype phase, it might be a good fit to experiment with. I recently began a new project and opted to use Pandora. This choice has not only accelerated my development process but also allowed me to contribute reporting bugs.

**Comment by bitbrain** [comment]
@pietru2004 thanks for writing this up! For questions, please checkout our [Github Discussions](https://github.com/bitbrain/pandora/discussions)

It is actually not obvious to go there so I'll update the README!

**Comment by pietru2004** [comment]
ok thanks for info
