### ISSUE TITLE
Icons Don't scale

### ISSUE THREAD

**Issue by pietru2004** [bitbrain/pandora#109]
if you download svg files and use them as icons...
![obraz](https://github.com/bitbrain/pandora/assets/51274570/33b6c688-dff8-4cc1-9eaf-b3f1924a2345)
they don't scale down

I basicaly downloaded some svgs from game-icons and well that is how it looks

**Comment by bitbrain** [comment]
@pietru2004 this is a Godot bug - icon .svgs need to be 16x16 pixels. Try the same with 

`@icon("my-icon.svg")` on custom scenes and you see a terrible surprise.

**Comment by pietru2004** [comment]
Erm 
1 is there fix on horizon for that ?
2 can't you use/allow people to use expand icon property?
Example from button
![obraz](https://github.com/bitbrain/pandora/assets/51274570/726c4ada-fa55-4b9c-8e6b-de71846b54ad)

**Comment by pietru2004** [comment]
or use
set_icon_region or set_icon_max_width ?
Under and above
https://docs.godotengine.org/en/stable/classes/class_treeitem.html#class-treeitem-method-set-icon-modulate

**Comment by bitbrain** [comment]
@pietru2004 feel free to raise a pull request!

**Comment by pietru2004** [comment]
I would, but my problem is school year that just started and I am in final class
I can try, but I can't promise anything

**Comment by pietru2004** [comment]
I tried it out and well 
![obraz](https://github.com/bitbrain/pandora/assets/51274570/1af1e695-0fcc-45a5-bce4-1c8dd3e03136)
![obraz](https://github.com/bitbrain/pandora/assets/51274570/9aaea497-fb01-493f-9571-c208af39a2a6)
20 seams as good amount of max pixels

**Comment by pietru2004** [comment]
this is 24
![obraz](https://github.com/bitbrain/pandora/assets/51274570/fa52c0ff-5270-473c-a04c-2930e4ca0429)
I think it could be selectable between 16 and max 28/32 pixels in steps of 4

**Comment by pietru2004** [comment]
I think it would be the same level of ease of base implement as 
https://github.com/bitbrain/pandora/discussions/107
https://github.com/bitbrain/pandora/issues/110

**Comment by bitbrain** [comment]
@pietru2004 you may also need to take editor scale into account.

**Comment by pietru2004** [comment]
I guess it could use editor_scale*desired_pixel_size, so .5 would give 8 pixels and 2 would 32 if input is 16... I would ned to look for way to get interface scale

**Comment by pietru2004** [comment]
so from what I see there is [EditorPlugin.get_editor_interface](https://docs.godotengine.org/en/stable/classes/class_editorplugin.html#class-editorplugin-method-get-editor-interface).

And on that you can run `get_editor_scale()`

**Comment by pietru2004** [comment]
I got once way to use interface to generate mesh preview...
![obraz](https://github.com/bitbrain/pandora/assets/51274570/e6ac81c5-8020-4561-923b-f0d8f226f740)
so it could be like `ei.get_editor_scale()`
