### ISSUE TITLE
Categories as Enums

### ISSUE THREAD

**Issue by pietru2004** [bitbrain/pandora#111]
I want to ask for ability to have Categories as class_names

I recently was trying to make smelting system, and it needed to only allow ores
well I got ID from the pandora panel, but well as you can see just dropping in ID of category -> 2, might not be best idea... what if ID changes and etc...
![obraz](https://github.com/bitbrain/pandora/assets/51274570/ed58e84d-3a25-442d-9fe5-d2e31d501fa6)

**Comment by mrfelipemartins** [comment]
You can use [custom scripts](https://bitbra.in/pandora/#/mastery/custom-scripts) for that.. since custom scripts extends PandoraEntity you could do something like this:

```gdscript
class_name Ore extends PandoraEntity
...
```

```gdscript
...
if not Pandora.get_entity(item) is Ore:
return
...
```

**Comment by pietru2004** [comment]
hm... I could, well it still would be nice to see ability to use categories as enums or custom classes

**Comment by pietru2004** [comment]
I found this... https://github.com/bitbrain/pandora/issues/63 seams this is planned...

**Comment by bitbrain** [comment]
@pietru2004 yep, #63 should solve your issue.
