### ISSUE TITLE
Icon not set on create

### ISSUE THREAD

**Issue by pietru2004** [bitbrain/pandora#112]
![obraz](https://github.com/bitbrain/pandora/assets/51274570/d520e644-9035-4363-9796-306280c66598)

if you create new item under category that has default icon changed it won't use that icon as default for that item(entity).
It might be wanted behaviour, but well I think it would be nice to have that as fetch category icon as default...

**Comment by bitbrain** [comment]
@pietru2004 strange, that should actually work. Are you using the latest godot-4.x branch version?

**Comment by pietru2004** [comment]
4.1.1
![obraz](https://github.com/bitbrain/pandora/assets/51274570/a85d101d-f874-4588-9526-33966efc4a80)
latest release of plugin I think
![obraz](https://github.com/bitbrain/pandora/assets/51274570/8d78c335-29ab-47d1-9768-c2bc94aacfc2)

**Comment by bitbrain** [comment]
@pietru2004 could you try the latest version https://github.com/bitbrain/pandora/archive/refs/heads/godot-4.x.zip and let me know if the issue persists?

**Comment by pietru2004** [comment]
Gona try it when I get home

**Comment by pietru2004** [comment]
I checked this and version from link works

**Comment by bitbrain** [comment]
@pietru2004 good to know - I will close this as "already fixed" but it will come with Alpha 3
