### ISSUE TITLE
🔋 auto-update addon inside the editor

### ISSUE THREAD

**Issue by bitbrain** [bitbrain/pandora#126]
Similar to other addons such as [Godot Dialogue Manager](https://github.com/nathanhoad/godot_dialogue_manager) we could introduce a button (where the version label is) to upgrade the addon.

**Comment by bitbrain** [comment]
Ensure to also update the docs, this then should close #113

**Comment by Nemesis-AS** [comment]
I'd like to work on this issue. But I have a question, let's say that there are multiple releases available to update, should the user be allowed to choose which version they'd like to update?

**Comment by Nemesis-AS** [comment]
Also, if there is an update with breaking changes, I'd suggest adding some sort of header in the release notes which can be read by the updater and displayed to the user within Godot so they don't end up breaking their project by updating.

An example of the breaking changes header would be 
`:#: Breaking Change 1`
`:#: Breaking Change 2`
Then the updater can look for :#: and display those lines to the user

**Comment by bitbrain** [comment]
> let's say that there are multiple releases available to update

In case a user "skips" a release, we should always offer them the latest version.

> Also, if there is an update with breaking changes

rendering the markdown from the release notes should be sufficient. In case of breaking changes, I will mention it in the Github release description.
