### ISSUE TITLE
Array exports

### ISSUE THREAD

**Issue by bitbrain** [bitbrain/pandora#131]
Ability to export arrays as such in any script:
```gdscript
@export var array:Array[PandoraEntity]
```
and even custom types:
```gdscript
@export var array:Array[CustomType]
```
Ensure to write unit tests for this, as well as update the documentation!

**Comment by russmatney** [comment]
I'm new to EditorInspectorPlugins, so there might be hidden issues here.... BUT! This tweak seems to support setting exported PandoraEntities in arrays: https://github.com/russmatney/dino/commit/c22d952fe24b4e6c9b8a13c4a17c4f9354e0819c

I'll keep toying with it to see if I run into any surprises, but just to share - maybe this is already available
