### ISSUE TITLE
📃 Property array support

### ISSUE THREAD

**Issue by bitbrain** [bitbrain/pandora#54]
> Refer [to the contributor docs](https://bitbra.in/pandora/#/contribute/adding-new-property) to learn how to generally add new properties to Pandora!

Similar to https://github.com/bitbrain/pandora/issues/95, we require a way to provide a "list" of entries - especially for recipes this is crucial.

Support any existing type, and via a `+` button additional elements can be added.

## Example use cases

- list of ingredients
- list of minerals to spawn
- factions that an NPC may be friendly with

**Comment by penghao123456** [comment]
Good, very good
