### ISSUE TITLE
Generate category ids

### ISSUE THREAD

**Issue by bitbrain** [bitbrain/pandora#63]
Currently, only entity ids are being generated. It would be useful to also include the categories to some extend.

**Comment by bitbrain** [comment]
Also update https://bitbra.in/pandora/#/api/access?id=is-category-check-by-name-constant when this is implemented to remove the "downside"

**Comment by imothee** [comment]
Did you have an idea of how you'd want to implement the output? I'm happy to take a stab at this since it's causing me to twist around the current implementation by maintaining a bunch of proxy enums/dictionaries.

**Comment by bitbrain** [comment]
@imothee feel free to come up with something and we can iterate over it.
