### ISSUE TITLE
🎯 Vector property

### ISSUE THREAD

**Issue by BenjaTK** [bitbrain/pandora#71]
> Refer [to the contributor docs](https://bitbra.in/pandora/#/contribute/adding-new-property) to learn how to generally add new properties to Pandora!

A Vector property (which could be Vector2, Vector3 — Vector2i and 3i would be nice but not necessary —) would help a lot.

**Comment by mrfelipemartins** [comment]
Just for future context: currently I am using Pandora to store Maps and in each map I have properties to store spawn position. Having vectors would make it easier since I don't need two properties for x y axis.
