### ISSUE TITLE
Cannot set reference field value

### ISSUE THREAD

**Issue by VojtaStruhar** [bitbrain/pandora#79]
Godot version: v4.1.stable.official [970459615]

**Describe the bug**
When setting a reference property value, error is printed and the change doesn't happen.

**To Reproduce**
1. Go to Pandora panel with the example dataset (inventory)
2. Under Items/Ores select CopperOre
3. Change the CopperOre's rarity from currently Legendary to any other
4. Error gets printed and the change doesn't go through

Error: `Pandora error: value <Resource#-9223369595769779648> is incompatible with type reference`

This happens even if I create a brand new category with new reference fields and items.

**Expected behavior**
The rarity of CopperOre should change and no error should be printed.

**Desktop**
 - OS: MacOS 13.4.1

**Comment by VojtaStruhar** [comment]
The issue is, that the `PandoraReference` class isn't considered of type `"reference"` and fails the [is_valid_type](https://github.com/bitbrain/pandora/blob/6c9e8b2136073a6721ddfb524ffb0bbf08a9f9e7/addons/pandora/model/property.gd#L184) check.

```gdscript
func(variant): return variant is PandoraEntity,
```

Adding `PandoraReference` to the type check should be fine, I think. I [tried it](https://github.com/VojtaStruhar/pandora/tree/fix/reference-dropdown), seemed to work just fine.

```gdscript
func(variant): return variant is PandoraEntity or variant is PandoraReference,
```

But I don't understand the codebase well enough (yet!) to be fully confident.

**Comment by bitbrain** [comment]
@VojtaStruhar the idea is that the reference gets created dynamically inside Pandora. From an API perspective, it should always be PandoraEntity.

Let me see today what the issue is here!

**Comment by VojtaStruhar** [comment]
I dug a little more and found, that after selecting entity from a dropdown, you wrap it in PandoraReference and then call `set_default_value` with it:

```gdscript
# reference_property.gd, _ready
entity_picker.entity_selected.connect(
  func(entity:PandoraEntity):
    var reference = PandoraReference.new(entity.get_entity_id(), 1 if entity is PandoraCategory else 0)
    _property.set_default_value(reference)
    property_value_changed.emit())
```

But in `set_default_value` you have a [very similar piece of code](https://github.com/bitbrain/pandora/blob/6b4449ae48cbc553931a388c51855164c93c63c8/addons/pandora/model/entity.gd#L54) that does the same thing conditionally:

```gdscript
if value is PandoraEntity:
  value = PandoraReference.new(value.get_entity_id(), PandoraReference.Type.CATEGORY if value is PandoraCategory else PandoraReference.Type.ENTITY)
```

I think that in the entity_picker, we are wrapping the entity in a PandoraReference too early! I tried to pass in just the entity, seems to work just fine. I had a look in the stored data too - it seems to add the override correctly:

![Copper ore rarity override - effect in stored data](https://github.com/bitbrain/pandora/assets/49688205/d570ca76-c5cc-4b2a-b2a7-3fdba2caecf0)

If this sounds good to you, I'll make a pull request, it's a one-liner :)
