### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by jog1t** [bitbrain/pandora#83]
**Is your feature request related to a problem? Please describe.**
Handling quests is a difficult task. Handling quests in a realizable and extensible way is impossible.

**Describe the solution you'd like**
A quest editor, similar to one with items, where each quest is an item in a list. Also, a graph view for seeing which quest depends on which. Codegen would generate quest ids, which can be referenced in the code to trigger or finish them.

**Describe alternatives you've considered**
There's no reliable solution for this in the Godot ecosystem yet.

**Additional context**
Having items and quests in one place would help developers maintain a clear and understandable project with a simple structure.

**Comment by bitbrain** [comment]
Pandora attempts to be generic, so there will never be a concept of "quest" embedded into its core.

However, people still may require a setup that helps them with the requirements you mentioned. Let me write up a discussion on this, as there are several bits to consider.

In the meantime, let me close this.

**Comment by bitbrain** [comment]
@jog1t feedback appreciated! https://github.com/bitbrain/pandora/discussions/84
